### PR TITLE
Add sensor topic

### PR DESCRIPTION
**Pull request by tabinohito**
This PR allows the mujoco sensor value bridge to ros:
https://github.com/tabinohito/MujocoRosUtils/blob/f79575ab04a4b9ad19107589b8e38fd14e3f42b9/xml/sample_mujoco_ros_utils.xml#L101C1-L106C14

### CODE REVIEW

**Comment by tabinohito** [comment]
Why this ci met error ?
According to the [API](https://mujoco.readthedocs.io/en/stable/APIreference/APItypes.html#mjtsensor).
The code looks correct.

**Comment by gergondet** [comment]
> Why this ci met error ?

`mjSENS_JOINTACTFRC` was introduced in MuJoCo 2.3.7 and the CI here builds against 2.3.5

You can update the version of MuJoCo used in CI here: https://github.com/isri-aist/MujocoRosUtils/blob/main/.github/workflows/ci.yaml#L39 (as well as other references to 2.3.5)

Ideally, you'd want to check the version within CMake to ensure this can build

**Comment by tabinohito** [comment]
@gergondet 
I add the check mujoco version on CMake and change ci mujoco version.
Perhaps this error may have occurred due to insufficient permissions when ci push the doxygen documents.
What should I do?

**Comment by gergondet** [comment]
> What should I do?

You need to disable this feature when the CI is not running on the main-repo (the problem happens because your PR branch is `main`)

You can change the condition here: https://github.com/isri-aist/MujocoRosUtils/blob/main/.github/workflows/ci.yaml#L27

From:
```
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ] && \
             [ "${{ matrix.build-type }}" == "RelWithDebInfo" ]
```
To:
```
          if [ "${{ github.repository}}" == "isri-aist/MujocoRosUtils"] &&  \
             [ "${{ matrix.os }}" == "ubuntu-20.04" ] && \
             [ "${{ matrix.build-type }}" == "RelWithDebInfo" ]
```

**Comment by tabinohito** [comment]
@gergondet 
Thank you for your information!
I'm able to success the ci .

**Comment by gergondet** [comment]
Hi @tabinohito 

Thanks for your effort. I have written the MuJoCo version in a more robust way (looking at the MuJoCo header rather than by guessing from the MuJoCo folder)

I will merge it now.

**Pull request merged**
